# Generated by Django 4.2.4 on 2024-05-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
